version: '3.9'

volumes:
  postgres_data:

networks:
  postgres-network:

services:
  flask:
    build: ./flask
    container_name: flask
    restart: "unless-stopped"
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - postgres-network
    env_file: .env

  db:
    image: postgres:12.19-bullseye
    container_name: postgres
    restart: "unless-stopped"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # NOTE - Better to use different .env files for different services
    env_file: .env
    networks:
      - postgres-network
