version: '3.9'

volumes:
  postgres_data:

networks:
  postgres-network:

services:
  flask:
    build: ./flask
    container_name: flask
    restart: "unless-stopped"
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - postgres-network
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:pass@postgres:5432/flask_db
    # TODO del vol
    volumes:
      - ./flask/:/usr/src/app/

  db:
    image: postgres:12.19-bullseye
    container_name: postgres
    restart: "unless-stopped"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: flask_db
    networks:
      - postgres-network
