version: '3.9'

volumes:
  postgres_data:

networks:
  postgres-network:

services:
  flask:
    build: ./flask
    container_name: flask
    restart: "unless-stopped"
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - postgres-network
    env_file: .env
    # NOTE - this is for development only
    volumes:
      - ./flask/src:/usr/src/app/src
      - ./flask/alembic:/usr/src/app/alembic

  db:
    image: postgres:12.19-bullseye
    container_name: postgres
    restart: "unless-stopped"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - postgres-network
